### PR TITLE
Fixed AIKONF7 BB/BARO skip [ci]

### PR DESCRIPTION
**Pull request by Kaiowarez**
aikonf7 didnt have baro, removed
bb wasnt fixed updated and working.

### CODE REVIEW

**Comment by nerdCopter** [comment]
needs to be "[skip ci]"  not "skip [ci]", 
you can type this to fixit (must be in branch):
`git commit --amend -m "Fixed AIKONF7 BB/BARO [skip ci]"`
then git push again, since PR is still open it will be included.
Thank you!

**Comment by nerdCopter** [comment]
you can also see that the build-tests are failing for your PR:   ;(
https://travis-ci.org/emuflight/EmuFlight/pull_requests

**Comment by Kaiowarez** [comment]
Ah yeah I talked to quick last night about it
My target template was sent in I renamed it as an MD file
But it's not letting me do a push, at work so I have no access to github
directly
Can I do cancel pull and redo a pull request?

**Comment by Kaiowarez** [comment]
Err not push I meant after I did a push a 2nd time it wouldn't let me do a
pull again

**Comment by gretel** [comment]
please review/redo this PR - at least the `SPEEDYBEEF7` target is not compiling.

keep file name casing in mind - see https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

did partially merge it to `master`, though. please branch another PR off that.

regards

**Pull request closed without merging**
