### PR TITLE
adding a few targets , MambaF722i2c, fpvcyclef710, matekf405se

### PR DESCRIPTION
**Pull request by Kaiowarez**

### CODE REVIEW

**Comment by nerdCopter** [comment]
@Kaiowarez , do i need to rebuild the modded/existing targets, or just build the new ones?

**Comment by Kaiowarez** [comment]
Made this fixes and additions a while back wasn't sure if I pr them 🤔

**Comment by Kaiowarez** [comment]
To be honest I lost track

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
* merged to master
* built/rebuilt for 0.3.3
* built/rebuilt for 0.3.2

**Comment by nerdCopter** [comment]
closes https://github.com/emuflight/EmuFlight/issues/414

**Pull request merged**
