### PR TITLE
port of betaflight#10243 - add optional high framerate on screen display

### PR DESCRIPTION
**Pull request by gretel**
port of https://github.com/betaflight/betaflight/pull/10243 - add optional high framerate on screen display

tested on `FURYF4OSD` using `osd_task_frequency = 125` 👍 

another contribution to the end-of-analogue-video-era 😸

### CODE REVIEW

**Comment by Quick-Flash** [comment]
lol I saw that this was added as well. while your going about adding all this code you think it would be to much trouble to make the dynamic notch filter no longer a "feature" and make it a filter you can turn on/off by setting the dynamic notch q to 0? doesn't make sense that there is 1 filter that is treated as a feature while no other filters are.

**Comment by gretel** [comment]
done for now.. can have a look.

**Comment by gretel** [comment]
> done for now.. can have a look.

so.. merge or trash?

**Review by Quick-Flash — DISMISSED** [review]
Lets get something in the wiki for this

**Comment by gretel** [comment]
nobody working on this anymore? there are plenty of pull requests open and all i see is video on betaflight.

**Comment by gretel** [comment]
tested on `MATEKF411`, `MATEKF411RX`, `HELIOSPRING`, `FURYF4OSD`, ..

**Comment by nerdCopter** [comment]
it works, but i get a rolling line on NTSC 160 (on `NBDHMBF4PRO`)
https://user-images.githubusercontent.com/56646290/102932242-87766100-4465-11eb-9b2f-73e31d4a1aa5.mp4

**Review by nerdCopter — APPROVED** [review]
* i think it's fine, can be tuned if needed to not cause sync-lines. default 60 is good.

**Pull request merged**
