### PR TITLE
default PID Denom 2 for F411

### LINKED ISSUE #915: F411 are often 100% cpu
* reports that F411 are often 100% fixable with pid-demon 2 or less filtering.
* suggest some logic near https://github.com/emuflight/EmuFlight/blob/c9cb676f1ed13222e80e7ee8dc00b65cb806b489/src/main/flight/pid.c#L87 to define pid-denom 2 `if defined (STM32F411xE)`

### PR DESCRIPTION
**Pull request by nerdCopter**
- resolves https://github.com/emuflight/EmuFlight/issues/915

### CODE REVIEW

**Comment by nerdCopter** [comment]
@Quick-Flash , @BeauBrewski  what do you think about this quick-fix for F411 denom?

**Comment by nerdCopter** [comment]
- tested on CRAZYBEEF4DX (F411) resulted **denom 2 and dshot300**
- tested SKYSTARSF405-AIO resulted denom 1 and dshot600
- tested PYDRODRONEF7 resulted denom 1 and dshot600
- tested HELIOSPRING resulted denom 1 and dshot600

**Comment by Quick-Flash** [comment]
No need for dshot 300 as a default. If hardware is setup poorly and but any dshot is required it'll run slower than dshot600 as well. So 600 is a better default imo.

**Comment by nerdCopter** [comment]
okay, thanks, reverted that part.

**Pull request merged**
