### PR TITLE
ICM426XX - Disable AFSR

### PR DESCRIPTION
**Pull request by nerdCopter**
* ICM426XX - Disable AFSR
* Betaflight: Disable ICM426XX AFSR feature to prevent stalls
* Ardupilot: AP_InertialSensor: fix for ICM42688 stuck gyro issue
these undocumented bits in register 0x4d control the "adaptive full
scale range" mode of the ICM42688. The feature is enabled by default
but has a bug where it gives "stuck" gyro values for short periods
(between 1ms and 2ms):, leading to a significant gyro bias at longer
time scales, enough to in some cases cause a vehicle to crash if it is
unable to switch to an alternative IMU
* Thanks to all participants here: https://github.com/betaflight/betaflight/issues/12970
* Thanks to @DutchFPV for quick-turnaround testing
* Thanks to Betaflight devs communications

Co-authored-by: Andrew Tridgell <andrew@tridgell.net>
Co-authored-by: Steve Evans <Steve@SCEvans.com>

### CODE REVIEW

**Comment by nerdCopter** [comment]
8k
debug_mode = GYRO_RAW
unsoldered hand-movements

[EMUF_BLACKBOX_LOG_20231024_103529-holding-wire.BBL.zip](https://github.com/emuflight/EmuFlight/files/13120413/EMUF_BLACKBOX_LOG_20231024_103529-holding-wire.BBL.zip)

**Comment by nerdCopter** [comment]
i'm unsure what to use: `spiBusReadRegister` or `spiReadRegMsk`. both seem to work. but BBL shows some different axis behavior.
left=spiBusReadRegister ; right=spiReadRegMsk (debug, X,Y,Z seemingly re-arranged or maybe just scaled differently)
image


EmuFlight did not have `spiReadRegMsk` before ICM426xx, which seems to only "wait" before calling `spiBusReadRegister`.
https://github.com/emuflight/EmuFlight/blob/c55b0d708bcd9d4d127a8ae5523861bddbadf5c3/src/main/drivers/bus_spi.c#L275-L279

**Review by Quick-Flash — APPROVED** [review]
This looks like it should fix the issue, before we merge it we should see if we can replicate the issue on the bench and then show it not happening after this fix.

**Comment by Quick-Flash** [comment]
> i'm unsure what to use: `spiBusReadRegister` or `spiReadRegMsk`. both seem to work. but BBL shows some different axis behavior. I don't have this FC mounted so i cannot flight-test :(
> 
> left=spiBusReadRegister ; right=spiReadRegMsk (debug, X,Y,Z seemingly re-arranged or maybe just scaled differently) image
> 
> EmuFlight did not have `spiReadRegMsk` before ICM426xx, which seems to only "wait" before calling `spiBusReadRegister`.
> 

Since you have an FC that works with this code, If your unsure what scaling or whatever it needs try using the gui to see what rotating the quad does. If you tilt the fc 90 degrees you should see the quad respond correctly to that and not take some extra time to correct, or see it overshoot. If thats the case then we know its working right.

**Comment by nerdCopter** [comment]
@Quick-Flash , 90 tilts seem to work fine, with the caveat that our Configurator can become out-of-sync with physical position if moved too rapidly. (tested with mpu6000 and bmi270, this is still true, but maybe worse with icm42688p, both this PR and master)

master vs fix (where fix uses `spiReadRegMsk`)
obvious ticks left, not on right
image

**Comment by Quick-Flash** [comment]
@nerdCopter can you test 90 degree pitch with `dcm_kp` and `dcm_ki` to zero? This will disable the accelerometer fusion. If 90 degree pitch without going to crazy works fine then I'll say it looks good to merge.

**Comment by nerdCopter** [comment]
still does it, but sensors tab looks good. maybe i'll wait for flight-test. or maybe just know consider Configurator is obsolete on setup page render.

**Comment by nerdCopter** [comment]
findings:
* flight test as good
* logging at 8k will cause undesired effect. flight-control is less responsive to stick-input.
* ICM4266p Configurator 3D render becomes unsynchronized in both EmuFlight and Betaflight. All gyro's seem to do but icm426xx is a bit more drastic.
* Sensors tab seems to be fine.
* i had concerns about using `spiReadRegMsk` versus `spiBusReadRegister` because they both had a bitwise OR operator (reg | 0x80), but it turns out that `reg | x80` is equal to `reg | 0x80 | 0x80`

**Pull request merged**
