### PR TITLE
Add GPS telemetry support to GHST protocol

### PR DESCRIPTION
**Pull request by augustozanellato**
Port to EmuFlight of betaflight/betaflight#10606

Note: this PR can't be tested yet because it depends on firmware for Ghost (and supporting OpenTX) that has yet to be released

### CODE REVIEW

**Comment by Igorshp** [comment]
Just saw this PR. @augustozanellato from your comment on IRC facebook page.

Great work. Will test it out this week

**Comment by nerdCopter** [comment]
any news?

**Comment by augustozanellato** [comment]
> any news?

I’m still waiting for @tonycake to provide me the unreleased firmware

**Comment by Quick-Flash** [comment]
any updates now?

**Comment by augustozanellato** [comment]
Still waiting for the test fw :/

**Comment by nerdCopter** [comment]
:(
Maybe Kevin has some clout to get you the firmware :shrug:

**Comment by Igorshp** [comment]
Hey guys, I just got access to beta firmware of ghost. I'll aim to have this tested this week

**Comment by augustozanellato** [comment]
@Igorshp any updates? Ghost fw with gps telem support went public a couple days ago and I should be able to test it in two weeks

**Comment by augustozanellato** [comment]
Hi, I'm sorry it took so long to test but I had some problems with my 5" running emuflight and I haven't been able to test the pr for a year or so.
Today I have finally been able to test the GPS telemetry and it looks to be working fine, all the data reported on the Tx is coherent with data from the osd, both gps coords and altitude are fine.

**Comment by augustozanellato** [comment]
Update: looks like the BF pull request this is based on was closed and another one was made (betaflight/betaflight#10744).

On a side note: if you are developing 1.0 based on bf4.3 is this pr still needed?

**Comment by augustozanellato** [comment]
Ok, I should be able to update the PR and test it on friday I think (if weather allows me to). Will keep you updated

**Comment by augustozanellato** [comment]
I updated the PR and tested it and it seems to be working fine. On my radio I receive the same sensors as I do on my BF 4.3 quad.
Please double check the changes I made because some things in the BF pull request weren't compiling on EmuFlight so I had to fix some errors manually.

**Comment by nerdCopter** [comment]
* @Igorshp , would you verify as well? -- Welcome to review/approve as well.  
* i'll wait for a second validation before merging.
* thank you all!

**Comment by nerdCopter** [comment]
@augustozanellato , no secondary feedback from 3rd party. ar you comfortable with it to merge into master?

**Comment by nerdCopter** [comment]
> > @augustozanellato , no secondary feedback from 3rd party. are you comfortable with it to merge into master?
> 
> From my limited testing it works correctly, just not sure if I want to be responsible for quads falling off the sky :D
 
lol.  i just looked. two things here: it's just telemetry :D . and i see another actually merged PR for this that has slight variation: https://github.com/betaflight/betaflight/pull/10744/files

image

image

are those pertinent here? or EmuF needs to be different?

**Comment by augustozanellato** [comment]
> > > @augustozanellato , no secondary feedback from 3rd party. are you comfortable with it to merge into master?
> > 
> > 
> > From my limited testing it works correctly, just not sure if I want to be responsible for quads falling off the sky :D
> 
> lol. i just looked. two things here: it's just telemetry :D . and i see another actually merged PR for this that has slight variation: https://github.com/betaflight/betaflight/pull/10744/files
> 
> image
> 
> image
> 
> are those pertinent here? or EmuF needs to be different?

IIRC I cross checked with other telemetry protocols in emu and they don’t have those checks, it has probably been added in BF 4.x

**Review by nerdCopter — APPROVED** [review]

**Pull request merged**
