### PR TITLE
TBS-Tracer mode-display

### PR DESCRIPTION
**Pull request by Kaiowarez**
added 250 for osd display for tracer users

### CODE REVIEW

**Comment by gretel** [comment]
tracer?

**Comment by nerdCopter** [comment]
@Kaiowarez , ehitaja said his TBS-Tracer shows mode 1 on both his Emu and his BF. so we will have to validate/verify proper mode number.

**Comment by Kaiowarez** [comment]
Okay will double check with trappy again

**Comment by OptimusTi** [comment]
I asked Trappy on FB and he said it's RFmode 1, [0..100%].

**Comment by gretel** [comment]
@OptimusTi maybe tbs.. trappy can come up with some documentation?

**Comment by nerdCopter** [comment]
* Closing this.
* Express LRS mode 5 will be 200. may have further conflict other than above notes.
* CRSFv3 in progress.

**Pull request closed without merging**
