### PR TITLE
1.0.0 rust

### PR DESCRIPTION
**Pull request by saidinesh5**
@Quick-Flash Here's a pull request for how to get started with Rust Integration in EmuFlight 1.0.0 . The code size is still slightly higher (~1kb) But overall, the integration was smooth. The idea is we move more and more functions to the rustemu crate (and delete them from the C codebase)

To test this out,

* Make sure you have Rust installed  ( https://www.rust-lang.org/tools/install )
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

* Restart the terminal to make sure your `PATH` variable can use the rustup command

* Make sure to install the bare metal arm toolchain for rust installed:

```
rustup target add thumbv7em-none-eabihf
```

Then you can build emuflight using the regular `Makefile`

```
make TARGET=STM32F411
```

Let me know if there are any issues, so I can fix them before this is merged.

### CODE REVIEW

**Comment by Quick-Flash** [comment]
Do you know any of the process of adding this to our automation system? as you can see it breaks some of our checks :(

**Comment by saidinesh5** [comment]
@Quick-Flash I couldn't find any logs on Codacy Static Code Analysis page. All it says is not analyzed: https://app.codacy.com/gh/emuflight/EmuFlight/commit?cid=659668051&fileBranchId=30902143

Can someone with access to the Static Analysis page login and see why it wasn't running?

Locally I made changes to the github builder workflow but that isn't even used in the 1.x branch so didn't push one.

**Comment by nerdCopter** [comment]
i'll see what i can do, i just enabled Codacy on the`emuflight:1.0.0-experimental` branch yesterday upon seeing the comments.

**Comment by nerdCopter** [comment]
fails even upon retires.  i've had this happen before, sometimes a new push repairs, sometimes not.
image

**Pull request closed without merging**
