### PR TITLE
do not merge- just travis testing internet solution

### PR DESCRIPTION
**Pull request by nerdCopter**

### CODE REVIEW

**Comment by Quick-Flash** [comment]
it appears this has worked... would you like it merged now?

**Comment by nerdCopter** [comment]
no, i rather restart older build.  unsure if this is 100% proper

**Comment by nerdCopter** [comment]
PR #145 worked without this.  therefore i think problem was travis-ci servers.

**Comment by Quick-Flash** [comment]
well i've tried rebuilding my stick pids branch a handful of times to no avail...

**Comment by gretel** [comment]
this wont fix because i deleted the caches manually.
pretty sure what needs to be done is this https://unix.stackexchange.com/questions/45583/argument-list-too-long-how-do-i-deal-with-it-without-changing-my-command
but i dont see any related change in this PR?
pleasse re-submit something related to the actual issue while not observing countereffects, only.

**Pull request closed without merging**
