### PR TITLE
initial BMI270 support - NORMAL config file 8192 bytes

### LINKED ISSUE #861: [feature request] BMI270 support
* No support for BMI270
* Been trying to get BMI270 code compiling for multiple weeks unsuccessfully :(

### PR DESCRIPTION
**Pull request by nerdCopter**
* WIP
* Initial BMI270 support
* tested as flyable
* needs Configurator synchronization (Config wrongly shows 8k, 4k, etc. loops)
* intend to remove target definitions from this PR
* may need fixes
* NORMAL config file (8192 bytes)
* OSR4 mode is default

This code is ported mostly from Betaflight and minimally iNav. Thanks to project teams and GPL licensed opensource.
Intention of porting "CRT/IOC/CAS" from FlightNG/ATBetaflight if possible. Portability unknown at this time.
https://github.com/betaflight/betaflight/blob/master/LICENSE
https://github.com/iNavFlight/inav/blob/master/LICENSE
https://github.com/flightng/atbetaflight/blob/4.3-bsp-rebase/LICENSE

Massive thanks to @Peck07 for investigating and fixing some pre-existing failed works.
Massive thanks to @BeauBrewski for target definitions and help.

Closes #861

Further notes. @Peck07 said he made it work by picking BF's "pre-SPI" changes.  So we need to verify if newer code exists to make bmi270 more efficient.  Should also investigate @DusKing1's bmi270 updates from https://github.com/flightng/atbetaflight

Co-authored-by: KarateBrot <Rm2k-Freak@web.de>
Co-authored-by: Steve Evans <Steve@SCEvans.com>
Co-authored-by: chrisrosser <chrisrosser91@gmail.com>
Co-authored-by: Dominic Clifton <dominic.clifton@cleanflight.com>
Co-authored-by: mikeller <github@ike.ch>
Co-authored-by: Bruce Luckcuck <github@etracer.net>
Co-authored-by: Martin Luessi <mluessi@gmail.com>
Co-authored-by: Peck07 <28628457+Peck07@users.noreply.github.com>
Co-authored-by: nerdCopter <56646290+nerdCopter@users.noreply.github.com>
Co-authored-by: Dusking1 <31283897+DusKing1@users.noreply.github.com>

### CODE REVIEW

**Comment by nerdCopter** [comment]
image

**Comment by DusKing1** [comment]
I'll look into this once I got some spare time...

**Comment by DusKing1** [comment]
Just some general idea:

- use the `normal` driver instead of the `maximum_fifo_driver`
- during the init, read the CAS register so to get the CAS factor
- add CAS compensation around the gyrodata

**Comment by nerdCopter** [comment]
* updated with master & icm426xx.
* ugly merges, but code is ready for continued efforts. -- will be squashed in the long-term.

**Comment by nerdCopter** [comment]
* i merged @Peck07 's normal driver reversion. it takes a whopping 22K extra per hex.  
* now we can look at ATBF changes and possible optimizaton.
* it would be nice and probably easy to "gate" sothing to beuild either drivers -- `#if define(USE_BMI270_FIFO)` type of stuff.

**Comment by nerdCopter** [comment]
@MADCHILLER and i found some hidden bug after merge of normal drivers SHA 1a0ffaf66.   although i'll talk about a specific target, it will be generalized bug.
compiling TMOTORF7 before and after. pinio works before, but not after. instead, USB_MSC_PIN takes over a PINIO resource.
i may have to rebase without the normal drivers and investigate.  will ponder on direction to go.

**Comment by nerdCopter** [comment]
for clarity on last comment... red is wrong, green is correct

```diff
--- NORMAL driver
+++ FIFO driver
@@ -1,9 +1,9 @@
-NORMAL driver
+FIFO driver
 # version
-# EmuFlight / TMTR_TMOTORF7 (TMR7) 0.4.2 Jun  8 2023 / 13:38:39 (uncommitted_20230608CDT) MSP API: 1.51
+# EmuFlight / TMTR_TMOTORF7 (TMR7) 0.4.2 Jun  9 2023 / 15:12:13 (c9cb676f1) MSP API: 1.51
 
 # resource
-resource OSD 1 C13
+resource BEEPER 1 C13
 resource MOTOR 1 C06
 resource MOTOR 2 C07
 resource MOTOR 3 B00
@@ -11,7 +11,7 @@
 resource MOTOR 5 B06
 resource MOTOR 6 B08
 resource PPM 1 A15
-resource TRANSPONDER 1 A08
+resource LED_STRIP 1 A08
 resource SERIAL_TX 1 A09
 resource SERIAL_TX 2 A02
 resource SERIAL_TX 3 C10
@@ -34,16 +34,16 @@
 resource SPI_MOSI 1 A07
 resource SPI_MOSI 2 B15
 resource SPI_MOSI 3 B05
-resource CAMERA_CONTROL 1 A15
-resource TIMUP 1 B09
+resource ESCSERIAL 1 A15
+resource CAMERA_CONTROL 1 B09
 resource ADC_BATT 1 C01
 resource ADC_RSSI 1 C03
 resource ADC_CURR 1 C02
 resource BARO_CS 1 C15
-resource USB_MSC_PIN 1 C14
+resource PINIO 1 C14
 resource FLASH_CS 1 C08
 resource OSD_CS 1 B12
-resource SPI_PREINIT_OPU 1 A04
-resource SPI_PREINIT_OPU 2 C15
-resource SPI_PREINIT_OPU 3 C08
-resource SPI_PREINIT_OPU 4 B12
+resource SPI_PREINIT_IPU 1 A04
+resource SPI_PREINIT_IPU 2 C15
+resource SPI_PREINIT_IPU 3 C08
+resource SPI_PREINIT_IPU 4 B12

```

**Comment by nerdCopter** [comment]
`BMI270_INT_EXTI` is not a valid define.
* could add parameter at src/main/sensors/gyro.c:688 or use existing `GYRO_1_EXTI_PIN` or `MPU_INT_EXTI`

off-subject, same is true for non-existent `ICM42688P_EXTI_PIN`

**Comment by nerdCopter** [comment]
* found that mpu6000 drivers and defines are required for bm270i-only target to work.
* will need to rectify in firmware source-code.

**Comment by nerdCopter** [comment]
* defining `USE_GYRO_EXTI` (and `USE_MPU_DATA_READY_SIGNAL`) breaks linking stage.
* have not found a need for it yet, however. - needs investigation.

**Comment by nerdCopter** [comment]
Closing this in favor of FIFO. https://github.com/emuflight/EmuFlight/pull/930

**Pull request closed without merging**
