### PR TITLE
Update serial-4way-if to v20005

### PR DESCRIPTION
**Pull request by 4712**
Reservation of an MCU_ID area to simplificate adding of upcoming BLHeli_32 MCU

### CODE REVIEW

**Comment by nerdCopter** [comment]
[EmuFlight_0.4.0_BETAFPVF405_Build_f4c9801d8__PR549.hex.zip](https://github.com/emuflight/EmuFlight/files/7008713/EmuFlight_0.4.0_BETAFPVF405_Build_f4c9801d8__PR549.hex.zip)

TYVM @4712!!! @SkylionFPV  is testing.

**Comment by SkylionFPV** [comment]
I just tested this with the above hex and it's working perfectly now =]

**Comment by Quick-Flash** [comment]
Lets just verify this works with jesc and blheli_s before we call it good.

**Comment by 4712** [comment]
@Quick-Flash there is no change for jesc and blheli_s, but verification is always good ;)

**Comment by SkylionFPV** [comment]
@Quick-Flash I just tested with betafpv f405 v3 20a blheli_s aiofc with the same target as above and it connects to blheli_s suite, blheli_s configurator for jesc, and bluejays configurator just fine

**Review by Quick-Flash — APPROVED** [review]
Thanks for the PR

**Pull request merged**
