### PR TITLE
Remove Unused SRAM2

### PR DESCRIPTION
**Pull request by JulioCesarMatias**

### CODE REVIEW

**Comment by nerdCopter** [comment]
@JulioCesarMatias , can you explain what this does in description?

**Comment by JulioCesarMatias** [comment]
> @JulioCesarMatias , can you explain what this does in description?


SRAM2 define is not used,and I think it won't be used in the future either.Maybe I may be wrong, but if you think otherwise,you can close this PR.

**Comment by nerdCopter** [comment]
* please keep it open. i defer to @Quick-Flash .
* i did not understand the PR is why i asked.

**Comment by nerdCopter** [comment]
i do not know enough about this subject to conclude a decision.

when searching for keyword, i find these
```shell
$ grep -Iirn SRAM2 src/
src/main/target/link/stm32_flash_f722.ld:38:    SRAM2 (rwx)             : ORIGIN = 0x2003C000, LENGTH = 16K
src/main/target/link/stm32_flash_f7_split.ld:128:  .sram2 (NOLOAD) :
src/main/target/link/stm32_flash_f7_split.ld:130:    /* This is used by the startup in order to initialize the .sram2 secion */
src/main/target/link/stm32_flash_f7_split.ld:131:    _ssram2 = .;         /* define a global symbol at sram2 start */
src/main/target/link/stm32_flash_f7_split.ld:132:    __sram2_start__ = _ssram2;
src/main/target/link/stm32_flash_f7_split.ld:133:    *(.sram2)
src/main/target/link/stm32_flash_f7_split.ld:134:    *(SORT_BY_ALIGNMENT(.sram2*))
src/main/target/link/stm32_flash_f7_split.ld:137:    _esram2 = .;         /* define a global symbol at sram2 end */
src/main/target/link/stm32_flash_f7_split.ld:138:    __sram2_end__ = _esram2;
src/main/target/link/stm32_flash_f7_split.ld:139:  } >SRAM2
src/main/target/link/stm32_flash_f74x.ld:40:    SRAM2 (rwx)         	: ORIGIN = 0x2004C000, LENGTH = 16K
src/main/target/system_stm32f4xx.c:845:    /* Configure and enable Bank1_SRAM2 */
src/main/target/system_stm32f4xx.c:851:    /* Configure and enable Bank1_SRAM2 */
src/main/target/system_stm32f4xx.c:857:      Bank1_SRAM2 is configured as follow:
src/main/target/system_stm32f4xx.c:867:      FSMC_NORSRAMInitStructure.FSMC_Bank = FSMC_Bank1_NORSRAM2;
src/main/target/system_stm32f4xx.c:892:      FMC_NORSRAMInitStructure.FMC_Bank = FMC_Bank1_NORSRAM2;
src/main/target/KISSFCV2F7/stm32_flash_f722_no_split.ld:36:    SRAM2 (rwx)             : ORIGIN = 0x2003C000, LENGTH = 16K
src/main/target/common_fc_pre.h:51:#define USE_SRAM2
src/main/target/common_fc_pre.h:70:#define USE_SRAM2
src/main/target/common_fc_pre.h:118:#ifdef USE_SRAM2
src/main/target/common_fc_pre.h:119:#define SRAM2                       __attribute__ ((section(".sram2"), aligned(4)))
src/main/target/common_fc_pre.h:121:#define SRAM2
src/main/startup/startup_stm32f746xx.s:115:  ldr  r2, =_ssram2
src/main/startup/startup_stm32f746xx.s:116:  b  LoopFillZerosram2
src/main/startup/startup_stm32f746xx.s:117:/* Zero fill the sram2 segment. */  
src/main/startup/startup_stm32f746xx.s:118:FillZerosram2:
src/main/startup/startup_stm32f746xx.s:122:LoopFillZerosram2:
src/main/startup/startup_stm32f746xx.s:123:  ldr  r3, = _esram2
src/main/startup/startup_stm32f746xx.s:125:  bcc  FillZerosram2
src/main/startup/startup_stm32f722xx.s:115:  ldr  r2, =_ssram2
src/main/startup/startup_stm32f722xx.s:116:  b  LoopFillZerosram2
src/main/startup/startup_stm32f722xx.s:117:/* Zero fill the sram2 segment. */  
src/main/startup/startup_stm32f722xx.s:118:FillZerosram2:
src/main/startup/startup_stm32f722xx.s:122:LoopFillZerosram2:
src/main/startup/startup_stm32f722xx.s:123:  ldr  r3, = _esram2
src/main/startup/startup_stm32f722xx.s:125:  bcc  FillZerosram2
src/main/startup/startup_stm32f745xx.s:115:  ldr  r2, =_ssram2
src/main/startup/startup_stm32f745xx.s:116:  b  LoopFillZerosram2
src/main/startup/startup_stm32f745xx.s:117:/* Zero fill the sram2 segment. */  
src/main/startup/startup_stm32f745xx.s:118:FillZerosram2:
src/main/startup/startup_stm32f745xx.s:122:LoopFillZerosram2:
src/main/startup/startup_stm32f745xx.s:123:  ldr  r3, = _esram2
src/main/startup/startup_stm32f745xx.s:125:  bcc  FillZerosram2
src/main/drivers/system_stm32f4xx.c:89:        RCC_AHB1Periph_SRAM2 |

```

**Comment by JulioCesarMatias** [comment]
> i do not know enough about this subject to conclude a decision.
> 
> when searching for keyword, i find these
> 
> ```shell
> $ grep -Iirn SRAM2 src/
> src/main/target/link/stm32_flash_f722.ld:38:    SRAM2 (rwx)             : ORIGIN = 0x2003C000, LENGTH = 16K
> src/main/target/link/stm32_flash_f7_split.ld:128:  .sram2 (NOLOAD) :
> src/main/target/link/stm32_flash_f7_split.ld:130:    /* This is used by the startup in order to initialize the .sram2 secion */
> src/main/target/link/stm32_flash_f7_split.ld:131:    _ssram2 = .;         /* define a global symbol at sram2 start */
> src/main/target/link/stm32_flash_f7_split.ld:132:    __sram2_start__ = _ssram2;
> src/main/target/link/stm32_flash_f7_split.ld:133:    *(.sram2)
> src/main/target/link/stm32_flash_f7_split.ld:134:    *(SORT_BY_ALIGNMENT(.sram2*))
> src/main/target/link/stm32_flash_f7_split.ld:137:    _esram2 = .;         /* define a global symbol at sram2 end */
> src/main/target/link/stm32_flash_f7_split.ld:138:    __sram2_end__ = _esram2;
> src/main/target/link/stm32_flash_f7_split.ld:139:  } >SRAM2
> src/main/target/link/stm32_flash_f74x.ld:40:    SRAM2 (rwx)         	: ORIGIN = 0x2004C000, LENGTH = 16K
> src/main/target/system_stm32f4xx.c:845:    /* Configure and enable Bank1_SRAM2 */
> src/main/target/system_stm32f4xx.c:851:    /* Configure and enable Bank1_SRAM2 */
> src/main/target/system_stm32f4xx.c:857:      Bank1_SRAM2 is configured as follow:
> src/main/target/system_stm32f4xx.c:867:      FSMC_NORSRAMInitStructure.FSMC_Bank = FSMC_Bank1_NORSRAM2;
> src/main/target/system_stm32f4xx.c:892:      FMC_NORSRAMInitStructure.FMC_Bank = FMC_Bank1_NORSRAM2;
> src/main/target/KISSFCV2F7/stm32_flash_f722_no_split.ld:36:    SRAM2 (rwx)             : ORIGIN = 0x2003C000, LENGTH = 16K
> src/main/target/common_fc_pre.h:51:#define USE_SRAM2
> src/main/target/common_fc_pre.h:70:#define USE_SRAM2
> src/main/target/common_fc_pre.h:118:#ifdef USE_SRAM2
> src/main/target/common_fc_pre.h:119:#define SRAM2                       __attribute__ ((section(".sram2"), aligned(4)))
> src/main/target/common_fc_pre.h:121:#define SRAM2
> src/main/startup/startup_stm32f746xx.s:115:  ldr  r2, =_ssram2
> src/main/startup/startup_stm32f746xx.s:116:  b  LoopFillZerosram2
> src/main/startup/startup_stm32f746xx.s:117:/* Zero fill the sram2 segment. */  
> src/main/startup/startup_stm32f746xx.s:118:FillZerosram2:
> src/main/startup/startup_stm32f746xx.s:122:LoopFillZerosram2:
> src/main/startup/startup_stm32f746xx.s:123:  ldr  r3, = _esram2
> src/main/startup/startup_stm32f746xx.s:125:  bcc  FillZerosram2
> src/main/startup/startup_stm32f722xx.s:115:  ldr  r2, =_ssram2
> src/main/startup/startup_stm32f722xx.s:116:  b  LoopFillZerosram2
> src/main/startup/startup_stm32f722xx.s:117:/* Zero fill the sram2 segment. */  
> src/main/startup/startup_stm32f722xx.s:118:FillZerosram2:
> src/main/startup/startup_stm32f722xx.s:122:LoopFillZerosram2:
> src/main/startup/startup_stm32f722xx.s:123:  ldr  r3, = _esram2
> src/main/startup/startup_stm32f722xx.s:125:  bcc  FillZerosram2
> src/main/startup/startup_stm32f745xx.s:115:  ldr  r2, =_ssram2
> src/main/startup/startup_stm32f745xx.s:116:  b  LoopFillZerosram2
> src/main/startup/startup_stm32f745xx.s:117:/* Zero fill the sram2 segment. */  
> src/main/startup/startup_stm32f745xx.s:118:FillZerosram2:
> src/main/startup/startup_stm32f745xx.s:122:LoopFillZerosram2:
> src/main/startup/startup_stm32f745xx.s:123:  ldr  r3, = _esram2
> src/main/startup/startup_stm32f745xx.s:125:  bcc  FillZerosram2
> src/main/drivers/system_stm32f4xx.c:89:        RCC_AHB1Periph_SRAM2 |
> ```

removing the definition from SRAM2 does not cause problems with these files. Since you're unsure, it's better to wait what Kevin will say about it.

**Pull request closed without merging**
