### PR TITLE
[FURYF4OSD] / [RUSHBLADEF7] Add BMP280 Support

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
https://github.com/emuflight/EmuFlight/issues/415

### CODE REVIEW

**Comment by JulioCesarMatias** [comment]
the .hex file to flash >> https://github.com/emuflight/EmuFlight/actions/runs/1128198469

**Comment by JulioCesarMatias** [comment]
@nerdCopter  
no MAG is enabled for this board (Fury4 and Fury4OSD)

**Comment by JulioCesarMatias** [comment]
> the .hex file to flash >> https://github.com/emuflight/EmuFlight/actions/runs/1129687484


updated link

**Comment by nerdCopter** [comment]
maybe easier to build local .hex
`make FURYF4OSD --always-make`  (result will be in `./obj/`)
than linking large zips that must be downloaded, extracted, and target found.

**Comment by JulioCesarMatias** [comment]
> @nerdCopter
> no MAG is enabled for this board (FuryF4 and FuryF4OSD)

@nerdCopter  about this?

**Comment by nerdCopter** [comment]
> > @nerdCopter
> > no MAG is enabled for this board (FuryF4 and FuryF4OSD)
> 
> @nerdCopter about this?

i don't understand, really.  i'm not knowledgeable about target resources.

**Comment by nerdCopter** [comment]
* feedback & conversations leading me to merge this.

**Review by nerdCopter — APPROVED** [review]

**Pull request merged**
