### PR TITLE
Add new VGOODRCF4 FC

### PR DESCRIPTION
**Pull request by Zlopi**
Brand Name: Eachine 
Item name: F4 Flight Controller
Main control chip: STM32F405
Gyro: MPU6000
Input Voltage: 2-4S Lipo
Black Box: NO
Barometer: NO
Firmware: VGRC/VGOODRC
F4 Buzzer Interface: YES
Betaflight OSD: AT7456E
UART6: RC
UART5: DJI
UART2: VTX
Weight: 3.6g
PCB Size: 24.6x24.6mm
Mounting Hole: 20x20mm
- Support PPM, IBUS, SBUS, DSMX Receiver

### CODE REVIEW

**Comment by nerdCopter** [comment]
Thank you for contributing!
```
Makefile:339: recipe for target 'obj/main/VGOODRCF4/drivers/accgyro/accgyro_mpu.o' failed
make[2]: Leaving directory '/home/runner/work/EmuFlight/EmuFlight'
make[2]: *** [obj/main/VGOODRCF4/drivers/accgyro/accgyro_mpu.o] Error 1
Makefile:443: recipe for target 'binary' failed
make[1]: Leaving directory '/home/runner/work/EmuFlight/EmuFlight'
Makefile:387: recipe for target 'VGOODRCF4' failed
make[1]: *** [binary] Error 2
make: *** [VGOODRCF4] Error 2
Error: Process completed with exit code 2.
```

**Comment by Kaiowarez** [comment]
I'll look at it when I get home

**Comment by Zlopi** [comment]
#define MPU6000_CS_PIN          PA15
#define MPU6000_SPI_INSTANCE    SPI3

**Comment by Zlopi** [comment]
How do you like it or not?

**Comment by nerdCopter** [comment]
Thank you @Zlopi , has it been tested? all things work, including camera control?
[VGOODRCF4.zip](https://github.com/emuflight/EmuFlight/files/5567122/VGOODRCF4.zip)

**Comment by Kaiowarez** [comment]
Looks like it'll compile properly and everything is correctly declared

**Comment by Zlopi** [comment]
> Thank you @Zlopi , has it been tested? all things work, including camera control?
> [VGOODRCF4.zip](https://github.com/emuflight/EmuFlight/files/5567122/VGOODRCF4.zip)

fixed camera control

**Review by nerdCopter — APPROVED** [review]

**Comment by Diversionpfe** [comment]
Hi,
Accept my apologies if this is not the right place to post this issue.

My 3in cinewhoop is based on Eachine's Tyro79 stack which has the above FC together with a 4-in-1 ESC that supports 20A constant current/25A peak current, ONESHOT 125/42, DSHOT 150/300/600, based on MCU EFM8BB21F16G-C.
I flashed the FC with the latest EmuFlight VGRC/VGOODRC and found out that my gyro has a 90 degrees CW displacement (YAW is ok but PITCH acts like ROLL and ROLL acts like PITCH when I hold the drone in my hand and I am looking the drawing in  SETUP screen).
Is this normal? Why can't the default values make the FC be 0 degrees oriented?
The only way I discovered to solve this is using CW 90degrees but the overall response looks a bit non linear when compared to VGRC/VGOODRCF4 firmware flashing in BF without any orientation displacement.
Also, and this happens regardeless I flash the 4 ESCs either with BLHeli or BlueJay, I have only one working motor. Physically is number 2 but it appears as Motor 1 in Motor Screen.
Am I missing something in my config?
Thanks in advance

**Comment by nerdCopter** [comment]
@Diversionpfe , you may join Discord for community assistance, but also maybe test `Quad X 1234` on Configuration tab (without orientation cw90).   https://discord.gg/emfqENw

Maybe there is another hardware version of vGoodF4 and this target is not the correct one?

**Comment by Diversionpfe** [comment]
> @Diversionpfe , you may join Discord for community assistance, but also maybe test `Quad X 1234` on Configuration tab (without orientation cw90). https://discord.gg/emfqENw
> 
> Maybe there is another hardware version of vGoodF4 and this target is not the correct one? Maybe the originator @Zlopi knows some additional information.

@nerdCopter , thkx for your reply. I'll check Discord for community assistance.
Let's hope @Zlopi knows some additional info.

**Comment by Zlopi** [comment]
It looks like this new board is different. I only have an old board. I build the firmware and tested it on it. You should probably create new board profile.

> Hi,
> Accept my apologies if this is not the right place to post this issue.
> 
> My 3in cinewhoop is based on Eachine's Tyro79 stack which has the above FC together with a 4-in-1 ESC that supports 20A constant current/25A peak current, ONESHOT 125/42, DSHOT 150/300/600, based on MCU EFM8BB21F16G-C.
> I flashed the FC with the latest EmuFlight VGRC/VGOODRC and found out that my gyro has a 90 degrees CW displacement (YAW is ok but PITCH acts like ROLL and ROLL acts like PITCH when I hold the drone in my hand and I am looking the drawing in SETUP screen).
> Is this normal? Why can't the default values make the FC be 0 degrees oriented?
> The only way I discovered to solve this is using CW 90degrees but the overall response looks a bit non linear when compared to VGRC/VGOODRCF4 firmware flashing in BF without any orientation displacement.
> Also, and this happens regardeless I flash the 4 ESCs either with BLHeli or BlueJay, I have only one working motor. Physically is number 2 but it appears as Motor 1 in Motor Screen.
> Am I missing something in my config?
> Thanks in advance

It looks like this new board is different. I only have an old board. I build the firmware and tested it on it. You should probably create new board profile.

**Comment by Diversionpfe** [comment]
Hi Zlopi,

Kaio Pryde left a new target on Discord and I've already flashed it in my
VGOODRCF4 FC.
Initially I was able to have motors M1 to M3 spinning which was already an
improvement from the original FC target where only M2 responded to M1
cursor on EmuFlight.
Kaio enabled 4way blheli interface and it solved the non spinning motor.
I am testing this new target in my 3" ducted cinewhoop and so far so good.
I have also BlueJay v0.11 98Hz flashed on my ESC
Another thing I had to change on setup was CW 270 for both gyro and accel
on EmuF configurator because Pitch and Roll where not displayed correctly
on Setup tab model drawing (pitch was acting as roll and vice versa).

Will continue to test and post any developments on Discord.

Keep safe !
PF



Zlopi ***@***.***> escreveu no dia quinta, 15/04/2021 à(s)
08:25:

**Pull request merged**
