### PR TITLE
purge SDS and WC (smartDtermSmooting and witchCraft)

### PR DESCRIPTION
**Pull request by nerdCopter**
* removes SmartDTermSmoothing
* remove WitchCraft

please validate code.

### CODE REVIEW

**Comment by Quick-Flash** [comment]
looks good to me, will the gui work be difficult?

**Review by Quick-Flash — APPROVED** [review]

**Comment by nerdCopter** [comment]
i think gui will be easy enough :crossed_fingers: , the kicker will be making sure expert-mode not re-enabling view for non-existing feature.

**Comment by Quick-Flash** [comment]
ok just lemme know if we should merge this before the gui work is done, we probably need to come up with some sort of standard for the future though, lol

**Review by nerdCopter — COMMENTED** [review]
fixed.

**Pull request merged**
