### PR TITLE
differentiate KakuteF7 V1.5

### PR DESCRIPTION
**Pull request by nerdCopter**
* differentiate  KAKUTEF7V15 from KAKUTEF7HDV
* defines camera-control, current-scale, and max7456 differently

### CODE REVIEW

**Comment by Kaiowarez** [comment]
Looks good @nerdcopter

**Comment by nerdCopter** [comment]
Vanadio reports V2 does not boot :( @Kaiowarez

**Comment by Kaiowarez** [comment]
Ah damn I'll look at it

**Comment by Kaiowarez** [comment]
I'll fix it

**Comment by nerdCopter** [comment]
@Kaiowarez this is correct to say V2 right, not v1.5?   i just need clarity before i keep requesting tests.

**Comment by nerdCopter** [comment]
report fail.

**Comment by nerdCopter** [comment]
closing this, giving up for the moment.

**Pull request closed without merging**
