### PR TITLE
fix the root cause which lead to the (unrelated) removal of `f3` targets

### PR DESCRIPTION
**Pull request by gretel**
when `GPS_RESCUE` was taken over it wasn't ported right so the code does not compile for `f3` targets. which lead to the removal of support for `f3` targets.

this PR re-adds support for targets with very small flash size (`f3`) by just adding some definitions.

for now, targets `OMNIBUS` and `CRAZYBEEF3FR` are included and flying fine for me.

```
Linking OMNIBUS
Memory region         Used Size  Region Size  %age Used
           FLASH:      216642 B       252 KB     83.95%
    FLASH_CONFIG:          0 GB         4 KB      0.00%
             RAM:       36252 B        40 KB     88.51%
             CCM:          2 KB         8 KB     25.00%
       MEMORY_B1:          0 GB         0 GB
```

```
Linking CRAZYBEEF3FR
Memory region         Used Size  Region Size  %age Used
           FLASH:      220622 B       252 KB     85.50%
    FLASH_CONFIG:          0 GB         4 KB      0.00%
             RAM:       37212 B        40 KB     90.85%
             CCM:          2 KB         8 KB     25.00%
       MEMORY_B1:          0 GB         0 GB
```

should be merged on https://github.com/emuflight/EmuFlight/pull/277.

### CODE REVIEW

**Comment by gretel** [comment]
in case you did not notice: the build setup is still broken.

**Comment by nerdCopter** [comment]
* Yes, Travis errors are intermittent --sometime they start working again without "fixing".
* I clicked `Try again` on this one.
* Travis no longer a requirement, but still triggers.
* github workflow action is being extended.
* Thank you very kindly @gretel

**Comment by gretel** [comment]
> * Yes, Travis errors are intermittent --sometime they start working again without "fixing".
> * I clicked `Try again` on this one.
> * Travis no longer a requirement, but still triggers.
> * github workflow action is being extended.
> * Thank you very kindly @gretel

just kick travis.

**Comment by gretel** [comment]
did not intend to close, was just commenting and hit the wrong button.

**Comment by loutwice** [comment]
> when `GPS_RESCUE` was taken over it wasn't ported right so the code does not compile for `f3` targets. which lead to the removal of support for `f3` targets.
> 
> this PR re-adds support for targets with very small flash size (`f3`) by just adding some definitions.
> 
> for now, targets `OMNIBUS` and `CRAZYBEEF3FR` are included and flying fine for me.
> 
> ```
> Linking OMNIBUS
> Memory region         Used Size  Region Size  %age Used
>            FLASH:      216642 B       252 KB     83.95%
>     FLASH_CONFIG:          0 GB         4 KB      0.00%
>              RAM:       36252 B        40 KB     88.51%
>              CCM:          2 KB         8 KB     25.00%
>        MEMORY_B1:          0 GB         0 GB
> ```
> 
> ```
> Linking CRAZYBEEF3FR
> Memory region         Used Size  Region Size  %age Used
>            FLASH:      220622 B       252 KB     85.50%
>     FLASH_CONFIG:          0 GB         4 KB      0.00%
>              RAM:       37212 B        40 KB     90.85%
>              CCM:          2 KB         8 KB     25.00%
>        MEMORY_B1:          0 GB         0 GB
> ```
> 
> should be merged on #277.

thanks  gretel !

**Pull request merged**
