### PR TITLE
IFRC_IFLIGHT_F745_AIO Voltage/Amp Fix

### PR DESCRIPTION
**Pull request by nerdCopter**
* IFRC_IFLIGHT_F745_AIO Voltage/Amp Fix 
* as per @Kaiowarez instruction
* fixed by @BeauBrewski 
* tested by @BeauBrewski

### CODE REVIEW

**Comment by nerdCopter** [comment]
@BeauBrewski , do you think you can inspect this, maybe get testers or fix it? or just add to you potential target fixes as well?

**Review by BeauBrewski — CHANGES_REQUESTED** [review]
Tested on a spare iflight_f745_aio v2 board I have that has same voltage pins and adc. Voltage was detected, however had to manually set voltage and current to ADC on battery tab in configurator.
Suggest adding at line 134:
```
#define DEFAULT_VOLTAGE_METER_SOURCE    VOLTAGE_METER_ADC
#define DEFAULT_CURRENT_METER_SOURCE    CURRENT_METER_ADC
#define CURRENT_METER_SCALE_DEFAULT     100
```

**Comment by nerdCopter** [comment]
> [.....] Suggest adding at line 134 in target.h [....]

do you know how to PR against a PR or 3rd party branch?
commit any tested code and PR to my branch, i'll merge.
_**if if that's too complex, we can close this PR altogether and you can make a new PR with everything needed.**_

**Review by BeauBrewski — APPROVED** [review]
Tested on similar FC and Voltage/Amp is now reading and on default.

**Review by BeauBrewski — APPROVED** [review]

**Comment by nerdCopter** [comment]
i dont know why, but it wont let me merge with only Beau's approval

**Comment by BeauBrewski** [comment]
> i dont know why, but it wont let me merge with only Beau's approval

is it because its my own code branch?

**Comment by nerdCopter** [comment]
second validation: ` shALKE: on the Voltage, I can see the correct battery voltage in emuflight config, as well as what's on the balance leads`

**Review by BeauBrewski — APPROVED** [review]

**Review by Quick-Flash — APPROVED** [review]

**Pull request merged**
