### PR TITLE
Add New DFR F722 DUAL HD FC

### PR DESCRIPTION
**Pull request by mStrangers**
Add a new target for the DFR F722 DUAL HD fc .

### CODE REVIEW

**Comment by nerdCopter** [comment]
@mStrangers , Is it tested 100%? if so i'll approve and merge and add to release assets for 0.3.2

**Comment by mStrangers** [comment]
yep it's tested

**Review by nerdCopter — APPROVED** [review]
Thank you!

**Comment by mStrangers** [comment]
you're welcome

**Pull request merged**
