### PR TITLE
Unified targets

### PR DESCRIPTION
**Pull request by Kaiowarez**
Still need to finish Flywoo stuff
and 2 more HGLRC targets
letting a Build run to see if theres any error

### CODE REVIEW

**Comment by nerdCopter** [comment]
@Kaiowarez , it wont try to build until these conflicts are fixed:
```
Conflicting files
src/main/target/MAMBAF722/config.c
src/main/target/MAMBAF722/target.h
src/main/target/MATEKF411SE/target.c
src/main/target/MATEKF411SE/target.h
src/main/target/SPEEDYBEEF7V2/target.c
src/main/target/STRIXF10/target.h
```

**Comment by nerdCopter** [comment]
`src/main/vcp_hal/Shikijo.url`  ?, lol

**Comment by nerdCopter** [comment]
`src/main/target/AIRB_AG3X/target.mk` needs modification:
```
ifeq ($(TARGET), AIRB_AG3XF4)
F405_TARGETS    += $(TARGET)
else
ifeq ($(TARGET), AIRB_AG3XF7)
F7X2RE_TARGETS  += $(TARGET)
else
```

**Comment by nerdCopter** [comment]
found this too, annoyed yet, lol
```
<<<<<<< HEAD:src/main/target/MAMBAF722/target.h
#define USE_I2C_DEVICE_1
#define I2C_DEVICE              (I2CDEV_1)
#define BARO_I2C_INSTANCE       (I2CDEV_1)
#if defined(MAMBAF722I2C)
#define I2C1_SCL                PB8        // SCL pad  PB10, shared with UART3TX
#define I2C1_SDA                PB9       // SDA pad  PB11, shared with UART3RX
#else
#define I2C1_SCL                NONE        // SCL pad  PB10, shared with UART3TX
#define I2C1_SDA                NONE        // SDA pad  PB11, shared with UART3RX
#endif
=======
#define USE_I2C_DEVICE_2
#define I2C_DEVICE              (I2CDEV_2)
#if defined(DIAT_MAMBAF722_I2C)
#define I2C2_SCL                PB8        // SCL pad  PB10, shared with UART3TX
#define I2C2_SDA                PB9        // SDA pad  PB11, shared with UART3RX
#else
#define I2C2_SCL                NONE        // SCL pad  PB10, shared with UART3TX
#define I2C2_SDA                NONE        // SDA pad  PB11, shared with UART3RX
#endif
#define BARO_I2C_INSTANCE       (I2CDEV_2)

>>>>>>> XXXXXXXXXXX:src/main/target/DIAT_MAMBAF722/target.h
```

**Comment by nerdCopter** [comment]
on my test branch, 63 came out without the 4-alphabetical-prefix:
```
EmuFlight_0.3.3_BEEBRAIN_BL_V2_WHOOP_INTL_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_BEEBRAIN_BL_V2_WHOOP_US_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_BEEROTORF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_CLRACINGF7DUAL_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_CRAZYBEEF4DX_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_CRAZYBEEF4FR_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_CRAZYBEEF4FS_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_CRAZYFLIE2BQ_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_CRAZYFLIE2_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_DFRF722DUALHD_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_FISHDRONEF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_FLYWOOF405_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_FOXEERF722V2_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_FPVCYCLEF710_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_GEPRC_XILOF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_HELIOSPRING_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_HIFIONRCF7_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_HMBF41S_FRSKY_INTL_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_HMBF41S_FRSKY_US_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_HMBF4PRO_INTL_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_HMBF4PRO_US_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_IFF4_MINI_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_JBF7_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_JHEF411_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_JHEF7DUAL_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KAKUTEF4V2_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KAKUTEF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KAKUTEF7HDV_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KAKUTEF7MINIV1_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KAKUTEF7MINIV2_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KAKUTEF7V15_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KAKUTEF7_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KISSFCV2F7_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KIWIF4V2_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KIWIF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_KROOZX_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_LUXF4OSD_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_LUXMINIF7_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MAMBAF722I2C_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MATEKF405SE_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MATEKF405_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MATEKF411RX_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MATEKF411_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MATEKF722HD_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MATEKF722PX_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MATEKF722SE_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MATEKF722_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MLTEMPF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MLTYPHF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_MODE2FLUX_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_OMNIBUSF4SD_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_OMNIBUSF4V6_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_PIRXF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_PLUMF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_REVOLTOSD_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_RUSHBLADEF7_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_SKYZONEF405_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_SPARKY2_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_SPEKTRUMF400_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_STACKX_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_SYNERGYF4_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_VRRACE_Build_uncommitted_20210318CDT.hex
EmuFlight_0.3.3_XRACERF4_Build_uncommitted_20210318CDT.hex
```

**Comment by Kaiowarez** [comment]
Yes that's the sub branch builds I still gotta go thru those.  Pretty much
all that's left now and the few fixes I need to do

**Pull request closed without merging**
