### PR TITLE
Support for Redpine SPI RX protocol from BF

### PR DESCRIPTION
**Pull request by pashky**
Any interest in Redpine RX protocol port (https://www.rcgroups.com/forums/showthread.php?3236043-Redpine-Lowest-latency-RC-protocol)? Not exactly mainstream feature, and probably not very relevant in the world where ELRS exists, but looks like some people asked for it in the past (#420) and there's already fleet of whoop AIO boards with built-in cc2500. 

Anyway, I was bored and got across it by pure chance, so here you go. I tested it briefly around home on MATEKF411RX (Tinyhawk), seems to work fine. RC latency is not what's holding back this particular quad, so can't comment on that part, but link was stable.

Unlike #444 I didn't even try to copy all BFs refactorings in SPI RX code that happened since 3.5. Not much point in doing that in 0.3.x branch. Instead I just hooked up older FrSkyXX and cc2500xx functions where appropriate following the style of other cc2500 protocols.

### CODE REVIEW

**Comment by Quick-Flash** [comment]
yes this is what we have been waiting for, thanks :)

**Review by Quick-Flash — APPROVED** [review]

**Comment by jakezilla** [comment]
Sorry, I don't know if it is proper to respond here (not a github expert) but this is super exciting! I wanted to revisit Redpine for the upcoming whoop season on my Mobula6 and my Meteor65.

**Comment by nerdCopter** [comment]
> Sorry, I don't know if it is proper to respond here (not a github expert) but this is super exciting! I wanted to revisit Redpine for the upcoming whoop season on my Mobula6 and my Meteor65.

Tell me target FC .hex, and i will give the .hex for testing.  Discord is a better place, but it's okay.

**Comment by Igorshp** [comment]
Just tested this on Tinyhawk2 Race, MATEKF411RX target.

Works pretty well!

Tested:
- binding from cli
- channels 1-4 have full resolution
- channels 5-16 ( 12 aux channels!!)  have binary state
- telemetry: N/A 
- Connection loss: link recovery is a little slow, takes 4 seconds to recover link.

Overall looks good! Great work!

**Comment by pashky** [comment]
Thank you @Igorshp for testing.

> Just tested this on Tinyhawk2 Race, MATEKF411RX target.
>     * Connection loss: link recovery is a little slow, takes 4 seconds to recover link.

I observed a bit of inconsistency here. I have a very particular corner behind a dishwasher at home where I always get rxloss if I sit in the farthest room, so mostly it was enough to take a couple of steps closer to instantly pick up link, but a few times it took noticeable amount of time. Ideally we need to compare it with BF, but I didn't have time yet. If shit weather persists I might try it on weekend...

> Overall looks good! Great work!

Oh come on, it's just pilfering code from a fork :)

**Comment by BeauBrewski** [comment]
On two separate Mobula6, flashed `CRAZYBEEF4FR` with Redpine.
Redpine didn't show as an option in configurator for SPI, so in CLI when using the set spi protocol = redpine command, then save, it would soft brick my flight controller and make it unable to connect via USB to computer. Would have to use boot button to DFU and reflash to original firmware. 

I'm guessing something is wrong with the `CRAZYBEEF4FR` target I was given to test Redpine with.

**Comment by pashky** [comment]
@BeauBrewski Sorry if it’s obvious, but did you go through full chip erase when flashing?

**Comment by BeauBrewski** [comment]
😂 Yes, every time. It only bricked the FC after I set to redpine protocol and saved in CLI.

**Comment by pashky** [comment]
@BeauBrewski right after flashing or have you applied a dump where it was bound on frsky_d? I remember I had to do manual dfu once, but cleaning up config fixed it. But I didn’t try it on crazybeef4 as I don’t have it, so it could be genuine hardware incompatibility.

**Comment by BeauBrewski** [comment]
@pashky did not copy any dump, just parts of the diff, and then went through and manually adjusted the basics. Everything worked fine with the firmware, until went into CLI and typed "set rx_spi_protocol = redpine" then typed "save". Configurator then auto-disconnected after "save" like normal. But then COM port wasn't found and Windows popped up saying unknown USB device. Unable to connect at all, or do any of the ImpulseRC or Zadig fixes. Only way to get it to work again was to go into DFU with boot button and reflash. Tried it on my second Mobula6, same thing. Everything worked fine, until entering the CLI command to set rx_spi_protocol = Redpine and saved. 
And just now for a 3rd time to double check, flashed the redpine `crazybeef4fr` .hex, did no modification at all except type "set rx_spi_protocol = redpine" in CLI and save. Boom, unable to detect COM.  

Everyone with `MatekF411Rx` fc seems to have no problem, so I'm guessing something is wrong with the compiled `CrazyBeef4FR` I have, and I don't see where anyone above who have had success were using a crazybee fc/mobula.

**Comment by BeauBrewski** [comment]
This is the .hex I have been testing.

[EmuFlight_0.3.6_CRAZYBEEF4FR_Build_293dbd36d__PR654RedpineSPI.zip](https://github.com/emuflight/EmuFlight/files/6992184/EmuFlight_0.3.6_CRAZYBEEF4FR_Build_293dbd36d__PR654RedpineSPI.zip)

**Comment by nerdCopter** [comment]
* option `REDPINE` will show in next EmuConfig release.
* this is merged to master and we will release soon.  i really hope it's a fluke or hardware specific.
* if something could be solved quickly, such would be good because release intended very soon.

**Comment by JP-SB** [comment]
Hi, Flashed 0.4.0 Yesterday to my Happymodel DiamondF4 ( Firmware target: CrazybeeF4FR).
After enabling RedPine and Saving, the FC becomes unresponsive until Flashed via Boot-Button.
I really want RedPine AND EMUF on my Moblite, so im willing to test everything if that helps.

**Comment by pashky** [comment]
> 
> 
> Hi, Flashed 0.4.0 Yesterday to my Happymodel DiamondF4 ( Firmware target: CrazybeeF4FR).
> After enabling RedPine and Saving, the FC becomes unresponsive until Flashed via Boot-Button.
> I really want RedPine AND EMUF on my Moblite, so im willing to test everything if that helps.

@JP-SB could you kindly try this build please? https://www.dropbox.com/s/2q999ye98j5g546/EmuFlight_0.4.0_CRAZYBEEF4FR_Build_uncommitted_20210829BST.hex?dl=0

**Comment by BeauBrewski** [comment]
Will be later tonight/tomorrow before I can test it but will update you!

**Comment by nerdCopter** [comment]
the committed PR build: [EmuFlight_0.4.0_MATEKF411RX_Build_b24c2f41b.hex.zip](https://github.com/emuflight/EmuFlight/files/7073144/EmuFlight_0.4.0_MATEKF411RX_Build_b24c2f41b.hex.zip)

**Comment by JP-SB** [comment]
@pashky Hi! Buld works fine! Thank You!

**Comment by BeauBrewski** [comment]
> @JP-SB could you kindly try this build please? https://www.dropbox.com/s/2q999ye98j5g546/EmuFlight_0.4.0_CRAZYBEEF4FR_Build_uncommitted_20210829BST.hex?dl=0
> 
> @BeauBrewski and you too?
Tested:
setup via configurator
binding from button
channels 1-4 have full resolution
channels 5-8 have binary state (did not test other channels)
had no connection loss. 
armed, turtle mode, flight mode changes all worked great.

**Comment by nerdCopter** [comment]
@BeauBrewski , is this stuff works, or of you need builds. or if this needs to be sent to emuconfig, you may need to contact other @ DEVS.  I'm evacuated from hurricane. emu not on my list of concerns.

**Pull request merged**
