### PR TITLE
Target JHEF_JHEF405PRO

### PR DESCRIPTION
**Pull request by BeauBrewski**
For merge to master. Tested on bench. Waiting for some feedback from Chris Teal @ DroneCo
https://github.com/emuflight/EmuFlight/issues/639

### CODE REVIEW

**Comment by BeauBrewski** [comment]
Bad feedback and had to make some changes. Will update files here when new build gets tested.

**Comment by BeauBrewski** [comment]
Having to double check baro issue if target vs driver.
Works in bf, not in Emu.

**Comment by BeauBrewski** [comment]
Driver currently unavailable for barometer; target functional otherwise.

**Review by nerdCopter — APPROVED** [review]
* approve with understanding of no Baro support

**Pull request merged**
