### PR TITLE
Add faster SquareRoot

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
https://github.com/iNavFlight/inav/pull/6977#issue-645715100

### CODE REVIEW

**Comment by Quick-Flash** [comment]
Thank you for this! We will need to port this over to 1.0.0

**Comment by Quick-Flash** [comment]
by the way, are you in our emuflight discord?

**Comment by JulioCesarMatias** [comment]
> a propósito, você está em nossa discórdia emuflight?


Hi Kevin, I'm not on Discord, I'm sorry but I don't speak fluent English, only Brazilian Portuguese.

**Comment by nerdCopter** [comment]
Test build 1739 and 1740 contain this.
https://github.com/emuflight/dev-unstable/releases/tag/hex-1739
https://github.com/emuflight/dev-unstable/releases/tag/hex-1740

I flew 6 packs containing this, without issue.

**Review by Quick-Flash — APPROVED** [review]

**Comment by DzikuVx** [comment]
I love those cross-project collaborations :)

**Pull request merged**
