### PR TITLE
Msp updating for horizon

### PR DESCRIPTION
**Pull request by loutwice**
Thank you for contributing to EmuFlight!

## Important considerations when opening a pull request:

1. Pull requests will only be accepted if they are opened against the `master` branch. Pull requests opened against other branches without prior consent from the maintainers will be closed;

2. Please follow the coding style guidlines: https://github.com/emuflight/EmuFlight/blob/master/docs/development/CodingStyle.md

3. Keep your pull requests as small and concise as possible. One pull request should only ever add / update one feature. If the change that you are proposing has a wider scope, consider splitting it over multiple pull requests. In particular, pull requests that combine changes to features and one or more new targets are not acceptable.

4. Ideally, a pull request should contain only one commit, with a descriptive message. If your changes use more than one commit, rebase / squash them into one commit before submitting a pull request. If you need to amend your pull request, make sure that the additional commit has a descriptive message, or - even better - use `git commit --amend` to amend your original commit.

5. All pull requests are reviewed. Be ready to receive constructive criticism, and to learn and improve your coding style. Also, be ready to clarify anything that isn't already sufficiently explained in the code and text of the pull request, and to defend your ideas.

6. If your pull request is a fix for one or more issues that are open in GitHub, add a comment to your pull request, and add the issue numbers of the issues that are fixed in the form `Fixes #<issue number>`. This will cause the issues to be closed when the pull request is merged;

7. Remove this Text :).

## Any questions?

Please join our discord server:
https://discord.gg/gdP9CwE

### CODE REVIEW

**Comment by loutwice** [comment]
> thanks. please remove the template part of the pull request message next time. regards

ahha ok sorry about that my friend

**Comment by nerdCopter** [comment]
* `Files changed 0`
* included in `msp_updating_for_horizon` which was merged.

Close or "squash and merge" empty delta?

**Comment by loutwice** [comment]
> * `Files changed 0`
> * included in `msp_updating_for_horizon` which was merged.
> 
> Close or "squash and merge" empty delta?

look the commit @ there is one file changed don't know why it didnt appear?

**Comment by nerdCopter** [comment]
the commit was included in squash-merge:
master vs commit:
image

**Pull request merged**
