### PR TITLE
Smart smoothing fix

### PR DESCRIPTION
**Pull request by Quick-Flash**
after adding a debug mode to smart smoothing I found that it did not work as expected. So I've gone and updated it. It now works a lot better. Added a change to the defaults as well now because of this. This is why logging can be so important :)

### CODE REVIEW

**Comment by nerdCopter** [comment]
does this change the range from 0-25?  if yes, need to adjust firmware variable range and i'll need to modify GUI.

**Comment by Quick-Flash** [comment]
> does this change the range from 0-25? if yes, need to adjust firmware variable range and i'll need to modify GUI.

no. i'm using 35 and am quite happy with the results. However, if we want to get this more solid before a merge I could test more to determine what a better maximum value would be, as i seriously doubt anyone should need to use a value of 250 (or even would be able to get that to fly well). I did change this code to limit the max that it can smooth as well. the most it will decrease dterm is to 25% where as before it could decrease it to nothing. Since changing this I found that I was having issues with that being to much and the quad bobbing around in level flight, but that change seemed to completely take care of that.

**Comment by Quick-Flash** [comment]
This works very well now that i've tweaked it a bit. I really do like how I can get this to fly. Should be good to merge any time.

**Comment by nerdCopter** [comment]
will merge as per discussion with QF.

**Pull request merged**
