### PR TITLE
Smith-Predictor on/off toggle [smith_predict_enabled]

### PR DESCRIPTION
**Pull request by Quick-Flash**
Enable/disable options for smith predictor. I'll let others deal with the MSP side of things.

### CODE REVIEW

**Comment by Quick-Flash** [comment]
> @Quick-Flash ,
> ```
> # get smith_predict_enabled
> smith_predict_enabled = 1
> Allowed range: 0 - 0
> ```
> ON|OFF would be better, yes?

Something must be wrong in settings.c. it should be an on/off

**Comment by nerdCopter** [comment]
fixed
```
# get smith_predict_enabled
smith_predict_enabled = OFF
Allowed values: OFF, ON
Default value: ON
```

**Comment by nerdCopter** [comment]
i'd like to investigate casting `smith_predict_str` to boolean before merging this.  maybe one is better than the other, but i want to see first.

**Comment by nerdCopter** [comment]
@Quick-Flash , if we use a toggle, should strength range be limited to `1` minimum?

**Comment by Quick-Flash** [comment]
> @Quick-Flash , if we use a toggle, should strength range be limited to `1` minimum?

Delay and strength need to be minimum of 0

**Comment by nerdCopter** [comment]
i'll add BBL header as well.

**Comment by nerdCopter** [comment]
image

**Review by nerdCopter — APPROVED** [review]

**Pull request merged**
