### PR TITLE
Change VTX powers labels

### PR DESCRIPTION
**Pull request by nerdCopter**
* this is @madChiller's branch

### CODE REVIEW

**Review by RiskoFPV — COMMENTED** [review]
Does the capitalization matter? is osd all uppercase anyway? do we want to make it more uniform inside the code?

**Comment by Quick-Flash** [comment]
> Does the capitalization matter? is osd all uppercase anyway? do we want to make it more uniform inside the code?

Yes capitalizing matters. All that the osd chip stores is capital letters. Lowercase letters do not work and display garbage.

**Comment by Quick-Flash** [comment]
this works, but do we want to do a dynamic implementation?

**Comment by RiskoFPV** [comment]
Tested and it shows LV1, LV2.. etc in the OSD.
VTX channel OSD element still shows single number, like: A:1:2 for power level 2

Should be good to go

**Review by Quick-Flash — APPROVED** [review]

**Pull request merged**
