### PR TITLE
Kaio created HGLRCF411 target

### PR DESCRIPTION
**Pull request by nerdCopter**
Kaio reported tested and working.

### CODE REVIEW

**Comment by Quick-Flash** [comment]
why can't this be merged yet?

**Comment by gretel** [comment]
because the status check have not finished yet. just look below please

**Comment by Quick-Flash** [comment]
> because the status checks have not finished yet. just look below please

Yes I have checked the status, but when I click to see details, it shows me this... 
image

**Comment by gretel** [comment]
maybe githup api glitched dunno try restarting the build

**Pull request merged**
