### PR TITLE
default 1.5khz logging

### PR DESCRIPTION
**Pull request by nerdCopter**
* default 1.5khz logging

### CODE REVIEW

**Comment by nerdCopter** [comment]
i believe @madchiller would prefer 2k as default, thoughts?

**Comment by madchiller** [comment]
> i believe @madchiller would prefer 2k as default, thoughts?

Not up to speed why we are changing default logging rates ..  however..  I do usually request 2k logs in general..  2k is best for most filter tuning, but 1k is all that’s needed for step responses…  maybe 1.5 is a happy default

**Comment by nerdCopter** [comment]
> > i believe @madchiller would prefer 2k as default, thoughts?
> 
> Not up to speed why we are changing default logging rates .. however.. I do usually request 2k logs in general.. 2k is best for most filter tuning, but 1k is all that’s needed for step responses… maybe 1.5 is a happy default

it's definitely debate-able on why to change defaults.  pilots continuously submitting logs for review with only 1Khz and no gyro_scaled.  I'm just trying to ease the burden.  Honestly, an alternative is to refuse to review any log not up to standards.  If nothing else, very good to discuss.

PR #819 also involved here.

**Comment by nerdCopter** [comment]
i think this one is acceptable and can be merged.

**Review by Quick-Flash — APPROVED** [review]

**Pull request merged**
