### PR TITLE
WIP: Redpi(peli)ne

### PR DESCRIPTION
**Pull request by Igorshp**

### CODE REVIEW

**Comment by Quick-Flash** [comment]
you tested this?

**Comment by Quick-Flash** [comment]
ahh, yeah you can't compile any fc with built in spi rx. This needs some work.

**Comment by Igorshp** [comment]
No, still working on it. Posted in case anyone wants to help

**Comment by Igorshp** [comment]
Resolved compiler issues.

Currently failing on linking state as it can't find implementations of certain functions.

To test this run:

```
make MATEKF411RX
```
or
```
make CRAZYBEEF4FR
```

**Comment by nerdCopter** [comment]
```
Linking MATEKF411RX 
Memory region         Used Size  Region Size  %age Used
           FLASH:       15103 B        16 KB     92.18%
    FLASH_CONFIG:          0 GB        16 KB      0.00%
          FLASH1:      316784 B       480 KB     64.45%
   SYSTEM_MEMORY:          0 GB        29 KB      0.00%
             RAM:       69520 B       128 KB     53.04%
       MEMORY_B1:          0 GB         0 GB
/tmp/tmp-2844OtOBL1yP7vzb/gcc-9-2020-q2/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: /tmp/EmuFlight_MATEKF411RX.elf.O8cbcT.ltrans6.ltrans.o: in function `redpineSpiDataReceived':
<artificial>:(.text+0x8d3c): undefined reference to `rxSpiLedToggle'
Makefile:327: recipe for target 'obj/main/EmuFlight_MATEKF411RX.elf' failed
make[2]: Leaving directory '/home/runner/work/EmuFlight/EmuFlight'
/tmp/tmp-2844OtOBL1yP7vzb/gcc-9-2020-q2/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: <artificial>:(.text+0x8d90): undefined reference to `rxSpiCheckBindRequested'
/tmp/tmp-2844OtOBL1yP7vzb/gcc-9-2020-q2/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: <artificial>:(.text+0x8dac): undefined reference to `rxSpiLedOn'
Makefile:443: recipe for target 'binary' failed
make[1]: Leaving directory '/home/runner/work/EmuFlight/EmuFlight'
Makefile:387: recipe for target 'MATEKF411RX' failed
/tmp/tmp-2844OtOBL1yP7vzb/gcc-9-2020-q2/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: <artificial>:(.text+0x8dc2): undefined reference to `rxSpiLedBlink'
/tmp/tmp-2844OtOBL1yP7vzb/gcc-9-2020-q2/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: <artificial>:(.text+0x8e6e): undefined reference to `rxSpiLedBlink'
/tmp/tmp-2844OtOBL1yP7vzb/gcc-9-2020-q2/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: <artificial>:(.text+0x8fde): undefined reference to `rxSpiCheckBindRequested'
/tmp/tmp-2844OtOBL1yP7vzb/gcc-9-2020-q2/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: <artificial>:(.text+0x9034): undefined reference to `rxSpiLedToggle'
/tmp/tmp-2844OtOBL1yP7vzb/gcc-9-2020-q2/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: <artificial>:(.text+0x90da): undefined reference to `rxSpiLedOn'
collect2: error: ld returned 1 exit status
make[2]: *** [obj/main/EmuFlight_MATEKF411RX.elf] Error 1
make[1]: *** [binary] Error 2
make: *** [MATEKF411RX] Error 2
Error: Process completed with exit code 2.
```

**Comment by Igorshp** [comment]
@nerdCopter sorry, forgot to push last commit that fixed linker issues. Please try again with latest code

I'm currently stuck trying to get it to bind.

**Comment by nerdCopter** [comment]
it does automatically, and seems to be succeeding. only time we are required to intervene is for build-fails-due-to-stall, then we can "re-run" them.

**Comment by Igorshp** [comment]
ah :) thought you're building localy on your system

**Comment by Igorshp** [comment]
I'm digging through bind code at the moment, Looks like the right parts are not being triggered.

**Comment by Igorshp** [comment]
Sigh this was hard to track down. I did not realise the order of protocols must match in 2 different places.
Setting REDPINE in cli essentially picked some other protocol.

Correct code now gets called, however it still does not bind.
It currently gets stuck on STATE_TUNING1 and does not progress further.
From what I can see, no valid packets are coming through

**Comment by howels** [comment]
Any further progress on this? Works very well in BetaFlight and would be a strong inclusion for EmuFlight.

**Comment by bengmo64** [comment]
Would love to see Redpine added to Emulflight

**Comment by Quick-Flash** [comment]
not needed anymore, closing

**Pull request closed without merging**
