### PR TITLE
IFRC_IFLIGHT_F745_AIO

### PR DESCRIPTION
**Pull request by nerdCopter**
* IFRC_IFLIGHT_F745_AIO @kaiowarez
* IFRC_IFLIGHT_F745_AIO LED @frizzle101101
* needs testing and feedback for LED's

### CODE REVIEW

**Comment by frizzle101101** [comment]
Am i able to just fix this

**Comment by frizzle101101** [comment]
How do i take over this pr

**Comment by nerdCopter** [comment]
> How do i take over this pr

i'm trying give access via github, if i see no way, then i will reply with CLI how-to fork the PR

**Comment by nerdCopter** [comment]
@frizzle101101 , do you use this: https://cli.github.com/ ?

```
git fetch --all
gh pr checkout 382
git checkout -b frizzle745
```
make your mods
test compile with `make IFRC_IFLIGHT_F745_AIO --always-make`
commit
```
`gh pr create`  #will make new PR, i'm okay to close My & Kaio's prior PR's

**Comment by nerdCopter** [comment]
@ techromancer reported no LED menu on this build.

**Comment by nerdCopter** [comment]
Superseded by #686

**Pull request closed without merging**
