### PR TITLE
port of betaflight#9878 - Added option to show cell value instead of batt value at stats screen

### PR DESCRIPTION
**Pull request by gretel**
let's push some more `osd` related changes in as long as the configurator is out of sync anyway 😁 

this includes some very minor formatting 🦊

### CODE REVIEW

**Comment by gretel** [comment]
don't get why the build was failing.

**Review by Quick-Flash — APPROVED** [review]
Looks good to me and should be the default imo

**Comment by gretel** [comment]
> Looks good to me and should be the default imo

agree

**Comment by nerdCopter** [comment]
```
./src/main/interface/settings.c:1001:139: error: 'osdConfig_t' {aka 'struct osdConfig_s'} has no member named 'logo_on_arming'
 1001 | NT8  | MASTER_VALUE | MODE_LOOKUP, .config.lookup = { TABLE_OSD_LOGO_ON_ARMING }, PG_OSD_CONFIG, offsetof(osdConfig_t, logo_on_arming) },
      |                                                                                                 ^~~~~~~~~~~~~~~~~~

./src/main/interface/settings.c:1002:106: error: 'osdConfig_t' {aka 'struct osdConfig_s'} has no member named 'logo_on_arming_duration'
 1002 | d_logo_on_arming_duration",VAR_UINT8  | MASTER_VALUE, .config.minmax = { 5, 50 }, PG_OSD_CONFIG, offsetof(osdConfig_t, logo_on_arming_duration) },
      |                                                                                                 ^~~~~~~~~~~~~~~~~~
```

Not directly related, but if needed, could hard reset branch and re-merge upstream/master (for squashing all the failed updates). 
Minor conflicts in osd.c & osd.h, upon doing so.
```
git reset --hard 8b517de63551cdfed1f5fbcb86cc890dbedc3e78
```

**Comment by nerdCopter** [comment]
`BATT (CELL)` 0.36v is not right. is it my config or the code?

**Comment by nerdCopter** [comment]
verified on second quad, this needs fix

**Comment by nerdCopter** [comment]
with modified code:
```diff
-            tfp_sprintf(buff, "%d.%02d%c", getBatteryAverageCellVoltage() / 100, getBatteryAverageCellVoltage() % 100, SYM_VOLT);
+            tfp_sprintf(buff, "%d.%1d%c", getBatteryAverageCellVoltage() / 10, getBatteryAverageCellVoltage() % 10, SYM_VOLT);
         }
         else {
-            tfp_sprintf(buff, "%d.%02d%c", getBatteryVoltage() / 100, getBatteryVoltage() % 100, SYM_VOLT);
+            tfp_sprintf(buff, "%d.%1d%c", getBatteryVoltage() / 10, getBatteryVoltage() % 10, SYM_VOLT);
         }
```

`set osd_stat_show_cell_value = ON` :



`set osd_stat_show_cell_value = OFF` :

**Review by Quick-Flash — APPROVED** [review]

**Pull request merged**
