### PR TITLE
Add OSD_PLUS_CODE

### PR DESCRIPTION
**Pull request by dentex**
Hello guys,
I wanted to add the Plus Code (ref: https://en.wikipedia.org/wiki/Open_Location_Code) as an alternative option in OSD for the GPS lat/lon entries. I ported it from INAV.
I like it because:
1) you can save one row in OSD
2) it's easier to enter this code in Google Maps (...when you have to retrieve your aircraft)

>  Plus Codes are created using latitude and longitude coordinates. These are converted from two long and complicated numbers into a single, shorter code. 

To add the plus_code in OSD, in the CLI type:
`set osd_plus_code_pos = 2538` or a similar position.
(In the configurator, the osd_plus_code_pos will be labeled as unknown1)

There are also a couple of settings:
```
# get plus
plus_code_digits = 11
Allowed range: 10 - 13

plus_code_short = OFF
Allowed range: OFF - ON
```
`plus_code_digits`: Total number of plus code digits (before shortening with `plus_code_short`).
Precision at the equator: 10=>13.9x13.9m; 11=>2.8x3.5m; 12=>56x87cm; 13=>11x22cm; default: 11

`plus_code_short`: Set this to drop the first 4 characters from a full Plus Code and save more OSD space.
A full Plus Code is a "Global Code" such as 7MJCH93V+7F having 8 characters before the “+” sign, while a short Plus Code is a "Local Code" such as H93V+7F. A Local Code appears in many places across the globe, so, in order to identify your position, you have to know roughly were you are located (you have to know the first 4 characters identifying your position).

### CODE REVIEW

**Comment by dentex** [comment]
I thought I had actually squashed the two commits in this pull request... :O

**Comment by nerdCopter** [comment]
we squash when merge, fwiw.

**Comment by dentex** [comment]
You mean it's ok anyway?

**Comment by Quick-Flash** [comment]
> You mean it's ok anyway?

looks ok to me, do you mind merging this into the 1.0.0 branch as well? this could also benefit from this change :)

**Comment by dentex** [comment]
> > You mean it's ok anyway?
> 
> looks ok to me, do you mind merging this into the 1.0.0 branch as well? this could also benefit from this change :)

Thanks!
If I understand correctly, do you want me to open another pull request pointing to the 1.0.0 branch, or was the message for @nerdCopter ?

**Comment by nerdCopter** [comment]
> > > You mean it's ok anyway?
> > 
> > 
> > looks ok to me, do you mind merging this into the 1.0.0 branch as well? this could also benefit from this change :)
> 
> Thanks!
> If I understand correctly, do you want me to open another pull request pointing to the 1.0.0 branch, or was the message for @nerdCopter ?

This would require new PR for 1.0.0 branch.  Thusly require new coding, since 1.0.0 is different (But i question does BF already have this?)

**Comment by nerdCopter** [comment]
please review Codacy checks. Maybe need fix, maybe not.
https://app.codacy.com/gh/emuflight/EmuFlight/pullRequest?prid=7684214

**Comment by dentex** [comment]
> This would require new PR for 1.0.0 branch. Thusly require new coding, since 1.0.0 is different (But i question does BF already have this?)
Understood. Would you point me to the exact 1.0.0 branch? There are a few ones.
(BF didn't have this when I switched last year, nor I think it has now)

**Comment by dentex** [comment]
> please review Codacy checks. Maybe need fix, maybe not.
> https://app.codacy.com/gh/emuflight/EmuFlight/pullRequest?prid=7684214

...it looks to me that `buffer` is always being zero terminated.

**Comment by Quick-Flash** [comment]
> > This would require new PR for 1.0.0 branch. Thusly require new coding, since 1.0.0 is different (But i question does BF already have this?)
> 
> Understood. Would you point me to the exact 1.0.0 branch? There are a few ones.
> (BF didn't have this when I switched last year, nor I think it has now)

Emuflight 1.0.0 would be the branch. That will eventually become the master branch.

**Comment by dentex** [comment]
> Emuflight 1.0.0 would be the branch. That will eventually become the master branch.

Ok thanks, I was looking only at branches starting with "1.0.0" in their name... 😑

**Comment by dentex** [comment]
> looks ok to me, do you mind merging this into the 1.0.0 branch as well? this could also benefit from this change :)

I was taking a look at the `Emuflight 1.0.0` brach and I noticed that the changes to include Open Location Codes have already been made. If correctly understood, 1.0.0 is based on a later version of Betaflight and they already added GPS plus codes: https://github.com/betaflight/betaflight/commit/37dbbd0755c1cd3e8823e84bc8c2bbda885315d3

**Review by Quick-Flash — APPROVED** [review]

**Pull request merged**
