### PR TITLE
master of none (and Main)

### PR DESCRIPTION
**Pull request by gretel**
shows travis build status for master, not Main
updated pull request template (age of emu)

### CODE REVIEW

**Comment by nerdCopter** [comment]
@gretel , if @Quick-Flash approves, could you mod ./makefile to include
`FC_VER := $(FC_VER_MAJOR).$(FC_VER_MINOR).$(FC_VER_PATCH)_$(REVISION)`
?
it would put short-version commit-number in filenames.

**Comment by gretel** [comment]
@nerdCopter thanks this is just a test to try the "new workflow" :) 
looks like a reasonable change, though.

**Comment by nerdCopter** [comment]
Thank you tremendously for all this complex work, clever and amazing!!  wishing you were still on Discord for communications.

**Comment by gretel** [comment]
@nerdCopter thanks-thanks - just few clicks here and there.

**Pull request merged**
