### PR TITLE
KAKUTEF7MINI camera control not-fix

### PR DESCRIPTION
**Pull request by gretel**
try to make the camera control pin usable by syncing with betaflight but when the resources gets assigned motor 2,4 cant spin up. looks like some time woe to me

### CODE REVIEW

**Comment by Kaiowarez** [comment]
> try to make the camera control pin usable by syncing with betaflight but when the resources gets assigned motor 2,4 cant spin up. looks like some time woe to me

just need a dump for the target based off BF and i'll see what i can do :)

**Comment by gretel** [comment]
@Kaiowarez dang dont have none. dont feel like flashing back now. going to use another pin.

**Comment by Kaiowarez** [comment]
ah no worries , if you feel like reflashing i'll fix the target for you

**Comment by gretel** [comment]
@Kaiowarez thanks! going to try to use `MOTOR 5` or sth.

**Pull request closed without merging**
