### PR TITLE
adding kakutef7v2 build routine

### PR DESCRIPTION
**Pull request by Kaiowarez**

### CODE REVIEW

**Comment by nerdCopter** [comment]
@Kaiowarez  , so for V2, we don't need:
```
#define MAX7456_SPI_INSTANCE    SPI3
#define MAX7456_SPI_CS_PIN      SPI1_NSS_PIN
```
?

and we dont need to skip baro for v2:
```
#if !defined(KAKUTEF7V2)
#define USE_BARO_BMP280
#endif
```
?

**Comment by Kaiowarez** [comment]
Need the max7456 for v2 that's the bf osd driver
V2 doesn't have baro?

**Comment by nerdCopter** [comment]
> Need the max7456 for v2 that's the bf osd driver V2 doesn't have baro?

 yes it has BMP280, i was using your screencap from Vanadio, but searched myself instead and found yes for Baro

**Comment by Kaiowarez** [comment]
Sometimes the unified config file also says baro, but the hardware isn't
there, we end up with i2c errors

**Comment by nerdCopter** [comment]
closing this one only because i put these mods into #305

**Pull request closed without merging**
