### PR TITLE
Add initial support for building EmuFlight in FreeBSD.

### PR DESCRIPTION
**Pull request by loos-br**
With this change, the necessary dependencies (gmake, arm-none-eabi-gcc,
arm-none-eabi-newlib, python) and the right incantantion, you can build
EmuFlight in FreeBSD.

### CODE REVIEW

**Comment by Quick-Flash** [comment]
whats freeBSD? and does this make compiling emuflight easier for many users? Thanks for the work.

**Comment by nerdCopter** [comment]
@Quick-Flash, FreeBSD is an operating system.
I certainly do not mind merging this, if it's complete enough for other end-users.
It's unclear what additional "incantation(s)" might be needed :))

**Comment by loos-br** [comment]
> @Quick-Flash, FreeBSD is an operating system.
> I certainly do not mind merging this, if it's complete enough for other end-users.
> It's unclear what additional "incantation(s)" might be needed :))

Nothing fancy... all I need is:

$ env TARGET=XILOF4 GCC_REQUIRED_VERSION=8.4.0 gmake

There is still an issue with the VFP build options (the FreeBSD packages are built with different settings).  I have a workaround in place but I'm waiting for a better weather to check my builds and if all goes well I will push more details.

But yes, the idea is provide a fully working build environment for end-users (this is probably the first step).

Thanks

**Review by nerdCopter — COMMENTED** [review]
~~can you separate Xilo from this PR please. ty!~~
merged XILO, update to this brings it clean.

**Review by nerdCopter — APPROVED** [review]
* LGTM.  @loos-br , will you want to add to this, or good to merge?

**Pull request merged**
