### PR TITLE
Fix level mode/horizon issues

### PR DESCRIPTION
**Pull request by Quick-Flash**
Hopefully this fix any issues with level mode or horizon.

### CODE REVIEW

**Comment by nerdCopter** [comment]
* reported working by @StratusFPV with exception of upside down does not autoflip, but this was by design from @PJC code-request.
* maybe need a mode-toggle of some sort.

**Review by nerdCopter — APPROVED** [review]
* approving this PR with openness to a PJC-mode toggle of some sort.
* do you want to keep the debug as is (roll only)?

**Comment by nerdCopter** [comment]
* July 22 [7:58 PM] @StratusFPV: `I tested horizon after getting my 5" but only for about 10 minutes; it got dark. It seems okay. It's definitely not as snappy as angle mode to the "level" position but it's going back. The forward on pitch seems a little slower than the rest of the inputs.`

**Comment by Quick-Flash** [comment]
i'll try to add a case to keep the old functionality now that I have a bit of time.

**Pull request merged**
