### PR TITLE
Added additional battery voltage field to OSD

### PR DESCRIPTION
**Pull request by mbilozub**
Fixed Battery average cell voltage for the DJI OSD

### CODE REVIEW

**Comment by loutwice** [comment]
thank you @mbilozub ! i have to validate it as weel will try soon !! thank you really much for your help

**Comment by Quick-Flash** [comment]
if this is working without issues we should merge it to both master and the 0.3.x maintenance branch

**Comment by nerdCopter** [comment]
whomever tests this should approve and merge both, ty.

**Comment by loutwice** [comment]
@mbilozub tested and approved ! thanks for contributing !

**Pull request merged**
